name: Test

on:
  push:
    branches: [ "master" ]
    paths:
      - "teia_sdk/**"
      - "tests/**"
      - "setup.py"
      - "requirements*"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "teia_sdk/**"
      - "tests/**"
      - "setup.py"
      - "requirements*"
      - ".github/workflows/test.yml"

permissions:
  contents: read

env:
  TEIA_API_KEY: "${{ secrets.TEIA_SDK_TEST_API_KEY }}"

jobs:
  autotester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          log-public-key: true
          ssh-private-key: |
            ${{ secrets.NEI_SSH }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements-teia.txt
            requirements-tests.txt
            requirements.txt
      - name: Setup pip and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Install applicaiton.
        run: |
          pip install .[teia]
      - name: Test application.
        run: pytest ./tests
